// web.daisyui/src/components/hal_collection/hal_collection_list.tsx
/**
 * HalCollectionList - Generic collection component for HAL resources
 *
 * This component automatically renders a table with:
 * - Inferred columns from embedded items
 * - Selection and bulk operations
 * - Action toolbar with create/refresh/bulk operations
 * - Field renderers based on data type
 * - Empty and loading states
 *
 * Checkboxes are only shown when bulkOperations is provided and has items.
 *
 * This is the main component that drastically reduces feature code.
 */

import type { ReactNode } from 'react';
import { Plus, RefreshCw } from 'lucide-react';
import { useHalCollection, type ColumnConfig } from '../../hooks/use_hal_collection';
import { useSelection } from '../../hooks/use_selection';
import { HalResourceRow } from './hal_resource_row';
import { type FieldRenderer } from './field_renderers';
import { type HalObject, type BulkOperation } from '@houseofwolves/serverlesslaunchpad.web.commons';

export interface HalCollectionListProps {
    resource: HalObject | null | undefined;
    onRefresh?: () => void;
    onCreate?: () => void;
    onRowClick?: (item: HalObject) => void;
    columnConfig?: ColumnConfig;
    customRenderers?: Record<string, FieldRenderer>;
    primaryKey?: string;
    emptyMessage?: string;
    emptyIcon?: React.ReactNode;
    showCreateButton?: boolean;
    showRefreshButton?: boolean;
    /** Whether a background refresh is in progress (spins the refresh icon) */
    refreshing?: boolean;
    selectableFilter?: (item: HalObject) => boolean;
    /** Page title to display in the header row */
    title?: string;
    /** Bulk operations to show when items are selected. Checkboxes only appear when this has items. */
    bulkOperations?: BulkOperation[];
}

/**
 * Generic HAL collection list component
 *
 * @example
 * ```tsx
 * // Minimal usage - everything automatic
 * <HalCollectionList
 *   resource={data}
 *   onRefresh={refresh}
 * />
 *
 * // With customization
 * <HalCollectionList
 *   resource={data}
 *   onRefresh={refresh}
 *   onCreate={() => setCreateModalOpen(true)}
 *   bulkOperations={[
 *     { id: 'delete', label: 'Delete Selected', variant: 'destructive', handler: handleBulkDelete }
 *   ]}
 *   columnConfig={{
 *     dateLastUsed: { nullText: "Never" }
 *   }}
 *   customRenderers={{
 *     status: (value, col, item) => <CustomStatusBadge item={item} />
 *   }}
 * />
 * ```
 */
export function HalCollectionList({
    resource,
    onRefresh,
    onCreate,
    onRowClick,
    columnConfig = {},
    customRenderers,
    primaryKey = 'id',
    emptyMessage = 'No items found',
    emptyIcon,
    showCreateButton = true,
    showRefreshButton = true,
    refreshing = false,
    selectableFilter,
    title,
    bulkOperations = [],
}: HalCollectionListProps) {
    const { items, columns, templates, isEmpty } = useHalCollection(resource, { columnConfig });

    // Detect primary key from first item if not provided
    const detectedPrimaryKey =
        items.length > 0
            ? Object.keys(items[0]).find((key) => key.toLowerCase().endsWith('id')) || primaryKey
            : primaryKey;

    const {
        selected,
        toggleSelection,
        toggleAll,
        clearSelection,
        isSelected,
        allSelected,
        hasSelection,
        count: selectedCount,
    } = useSelection(items, detectedPrimaryKey);

    // Get templates from resource
    const createTemplate = templates?.default || templates?.create;

    // Checkboxes are shown only when bulk operations are defined
    const showCheckboxes = bulkOperations.length > 0;

    // Handle create action
    const handleCreate = () => {
        if (onCreate) {
            onCreate();
        }
    };

    // Handle refresh action
    const handleRefresh = () => {
        if (onRefresh) {
            onRefresh();
        }
    };

    // Handle select all checkbox - only select selectable items
    const handleSelectAll = () => {
        if (selectableFilter) {
            // Filter items to only include selectable ones
            const selectableItems = items.filter(selectableFilter);
            const selectableIds = selectableItems.map(item => item[detectedPrimaryKey]);

            // Check if all selectable items are selected
            const allSelectableSelected = selectableIds.every(id => isSelected(id));

            if (allSelectableSelected) {
                // Deselect all
                clearSelection();
            } else {
                // Select all selectable items
                selectableIds.forEach(id => {
                    if (!isSelected(id)) {
                        toggleSelection(id);
                    }
                });
            }
        } else {
            toggleAll();
        }
    };

    // Empty state
    if (isEmpty) {
        return (
            <div className="space-y-4">
                {/* Page title */}
                {title && (
                    <div className="space-y-1">
                        <h1 className="text-3xl font-bold tracking-tight">{title}</h1>
                    </div>
                )}

                {/* Action toolbar */}
                <div className="flex items-center justify-end gap-2">
                    {showCreateButton && createTemplate && (
                        <button className="btn btn-sm border border-base-300 bg-base-100 hover:bg-base-200" onClick={handleCreate}>
                            <Plus className="w-4 h-4 mr-2" />
                            {createTemplate.title || 'Create'}
                        </button>
                    )}
                    {showRefreshButton && (
                        <button className="btn btn-sm border border-base-300 bg-base-100 hover:bg-base-200" onClick={handleRefresh} disabled={refreshing}>
                            <RefreshCw className={`w-4 h-4 mr-2 ${refreshing ? 'animate-spin' : ''}`} />
                            Refresh
                        </button>
                    )}
                </div>

                {/* Empty state card */}
                <div className="card bg-base-100 shadow-xl">
                    <div className="card-body items-center text-center py-12">
                        {emptyIcon && <div className="mb-4 text-base-content/50">{emptyIcon}</div>}
                        <h3 className="card-title">No Items</h3>
                        <p className="text-sm text-base-content/70 mb-6">{emptyMessage}</p>
                        {showCreateButton && createTemplate && (
                            <button className="btn border border-base-300 bg-base-100 hover:bg-base-200" onClick={handleCreate}>
                                <Plus className="w-4 h-4 mr-2" />
                                {createTemplate.title || 'Create First Item'}
                            </button>
                        )}
                    </div>
                </div>
            </div>
        );
    }

    return (
        <div className="space-y-4">
            {/* Page title */}
            {title && (
                <div className="space-y-1">
                    <h1 className="text-3xl font-bold tracking-tight">{title}</h1>
                </div>
            )}

            {/* Action toolbar */}
            <div className="flex items-center justify-between">
                {hasSelection ? (
                    <div className="flex items-center gap-4">
                        <span className="text-sm text-base-content/70">
                            {selectedCount} item{selectedCount > 1 ? 's' : ''} selected
                        </span>
                        <button className="btn btn-ghost btn-xs" onClick={clearSelection}>
                            Clear
                        </button>
                    </div>
                ) : (
                    <div />
                )}

                <div className="flex items-center gap-2">
                    {hasSelection && bulkOperations.map((op) => (
                        <button
                            key={op.id}
                            className={`btn btn-sm ${op.variant === 'destructive' ? 'btn-error' : 'border border-base-300 bg-base-100 hover:bg-base-200'}`}
                            onClick={() => op.handler(Array.from(selected), clearSelection)}
                            disabled={op.disabled?.(Array.from(selected))}
                        >
                            {op.icon ? <span className="mr-2">{op.icon as ReactNode}</span> : null}
                            {op.label}
                        </button>
                    ))}
                    {showCreateButton && createTemplate && (
                        <button className="btn btn-sm border border-base-300 bg-base-100 hover:bg-base-200" onClick={handleCreate}>
                            <Plus className="w-4 h-4 mr-2" />
                            {createTemplate.title || 'Create'}
                        </button>
                    )}
                    {showRefreshButton && (
                        <button className="btn btn-sm border border-base-300 bg-base-100 hover:bg-base-200" onClick={handleRefresh} disabled={refreshing}>
                            <RefreshCw className={`w-4 h-4 mr-2 ${refreshing ? 'animate-spin' : ''}`} />
                            Refresh
                        </button>
                    )}
                </div>
            </div>

            {/* Table */}
            <div className="card bg-base-100 shadow-xl">
                <div className="overflow-x-auto">
                    <table className="table table-fixed">
                        <thead>
                            <tr>
                                {/* Select all checkbox */}
                                {showCheckboxes && (
                                    <th className="w-12">
                                        <input
                                            type="checkbox"
                                            className="checkbox checkbox-sm"
                                            checked={allSelected}
                                            onChange={handleSelectAll}
                                            aria-label="Select all"
                                        />
                                    </th>
                                )}

                                {/* Column headers */}
                                {columns.map((col) => (
                                    <th key={col.key} style={{ width: col.width }}>
                                        {col.label}
                                    </th>
                                ))}
                            </tr>
                        </thead>
                        <tbody>
                            {items.map((item) => {
                                const itemId = item[detectedPrimaryKey];
                                const isItemSelectable = showCheckboxes && (!selectableFilter || selectableFilter(item));

                                return (
                                    <HalResourceRow
                                        key={itemId || Math.random()}
                                        item={item}
                                        columns={columns}
                                        showCheckboxColumn={showCheckboxes}
                                        selectable={isItemSelectable}
                                        selected={isSelected(itemId)}
                                        onToggleSelect={() => toggleSelection(itemId)}
                                        onRowClick={onRowClick}
                                        customRenderers={customRenderers}
                                    />
                                );
                            })}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    );
}

// web.svelte/src/lib/components/hal_collection/HalCollectionList.svelte
<script lang="ts">
	/**
	 * HalCollectionList - Generic collection component for HAL resources
	 *
	 * This component automatically renders a table with:
	 * - Inferred columns from embedded items
	 * - Selection and bulk operations
	 * - Action toolbar with create/refresh/delete
	 * - Field renderers based on data type
	 * - Empty and loading states
	 */

	import { Plus, RefreshCw } from 'lucide-svelte';
	import { processCollection, SelectionManager, type ColumnOverride } from '$lib/utils/collection_utils';
	import HalResourceRow from './HalResourceRow.svelte';
	import type { HalObject, BulkOperation } from '@houseofwolves/serverlesslaunchpad.web.commons';
	import type { FieldRenderer } from './field_renderers';
	import { cn } from '$lib/utils';
	import Button from '$lib/components/ui/button.svelte';

	// Props
	export let resource: HalObject | null | undefined;
	export let onRefresh: (() => void) | undefined = undefined;
	export let onCreate: (() => void) | undefined = undefined;
	export let bulkOperations: BulkOperation[] = [];
	export let onRowClick: ((item: HalObject) => void) | undefined = undefined;
	export let columnConfig: Record<string, ColumnOverride> = {};
	export let customRenderers: Record<string, FieldRenderer> | undefined = undefined;
	export let primaryKey = 'id';
	export let emptyMessage = 'No items found';
	export let emptyIcon: any = undefined;
	export let showCreateButton = true;
	export let showRefreshButton = true;
	/** Whether a background refresh is in progress (spins the refresh icon) */
	export let refreshing = false;
	export let selectableFilter: ((item: HalObject) => boolean) | undefined = undefined;
	/** Page title to display in the header row */
	export let title: string | undefined = undefined;

	// Process collection
	$: result = processCollection(resource, { columnConfig });
	$: ({ items, columns, templates, isEmpty } = result);

	// Detect primary key
	$: detectedPrimaryKey =
		items.length > 0
			? Object.keys(items[0]).find((key) => key.toLowerCase().endsWith('id')) || primaryKey
			: primaryKey;

	// Selection management - persistent state
	let selectedSet = new Set<string>();

	// Reactive selection state
	$: selectableItems = selectableFilter ? items.filter(selectableFilter) : items;
	$: selected = Array.from(selectedSet);
	$: allSelected = selectableItems.length > 0 && selectedSet.size === selectableItems.length;
	$: hasSelection = selectedSet.size > 0;
	$: selectedCount = selectedSet.size;

	function isSelected(id: string): boolean {
		return selectedSet.has(id);
	}

	function toggleSelection(id: string) {
		if (selectedSet.has(id)) {
			selectedSet.delete(id);
		} else {
			selectedSet.add(id);
		}
		// Force reactivity
		selectedSet = selectedSet;
	}

	function clearSelection() {
		selectedSet.clear();
		selectedSet = selectedSet;
	}

	function toggleAllSelection() {
		if (allSelected) {
			selectedSet.clear();
		} else {
			selectableItems.forEach(item => {
				const id = item[detectedPrimaryKey];
				if (id) selectedSet.add(id);
			});
		}
		selectedSet = selectedSet;
	}

	// Templates
	$: createTemplate = templates?.default || templates?.create;

	// Show checkboxes only if bulk operations are defined
	$: showCheckboxes = bulkOperations.length > 0;

	// Handlers
	function handleCreate() {
		if (onCreate) onCreate();
	}

	function handleRefresh() {
		if (onRefresh) onRefresh();
	}

	function handleBulkOperation(operation: BulkOperation) {
		if (hasSelection) {
			operation.handler(selected, clearSelection);
		}
	}

	function handleSelectAll() {
		toggleAllSelection();
	}

	function handleToggleSelection(itemId: string) {
		toggleSelection(itemId);
	}

	function handleRowClick(item: HalObject) {
		if (onRowClick) onRowClick(item);
	}
</script>

{#if isEmpty}
	<div class="space-y-4">
		<!-- Page title -->
		{#if title}
			<div class="space-y-1">
				<h1 class="text-3xl font-bold tracking-tight">{title}</h1>
			</div>
		{/if}

		<!-- Action toolbar -->
		<div class="flex items-center justify-end gap-2">
			{#if showCreateButton && createTemplate}
				<Button variant="outline" size="sm" on:click={handleCreate}>
					<Plus class="w-4 h-4 mr-2" />
					{createTemplate.title || 'Create'}
				</Button>
			{/if}
			{#if showRefreshButton}
				<Button variant="outline" size="sm" on:click={handleRefresh} disabled={refreshing}>
					<RefreshCw class={cn("w-4 h-4 mr-2", refreshing && "animate-spin")} />
					Refresh
				</Button>
			{/if}
		</div>

		<!-- Empty state card -->
		<div class="rounded-xl border bg-card text-card-foreground shadow">
			<div class="flex flex-col items-center justify-center text-center p-12">
				{#if emptyIcon}
					<div class="mb-4 text-muted-foreground">
						<svelte:component this={emptyIcon} class="w-12 h-12" />
					</div>
				{/if}
				<h3 class="text-2xl font-semibold leading-none tracking-tight">No Items</h3>
				<p class="text-sm text-muted-foreground mt-2 mb-6">{emptyMessage}</p>
				{#if showCreateButton && createTemplate}
					<Button variant="outline" on:click={handleCreate}>
						<Plus class="w-4 h-4 mr-2" />
						{createTemplate.title || 'Create First Item'}
					</Button>
				{/if}
			</div>
		</div>
	</div>
{:else}
	<div class="space-y-4">
		<!-- Page title -->
		{#if title}
			<div class="space-y-1">
				<h1 class="text-3xl font-bold tracking-tight">{title}</h1>
			</div>
		{/if}

		<!-- Action toolbar -->
		<div class="flex items-center justify-between">
			{#if hasSelection}
				<div class="flex items-center gap-4">
					<span class="text-sm text-muted-foreground">
						{selectedCount} item{selectedCount > 1 ? 's' : ''} selected
					</span>
					<Button
						variant="ghost"
						size="sm"
						on:click={() => {
							clearSelection();
						}}
					>
						Clear
					</Button>
				</div>
			{:else}
				<div></div>
			{/if}

			<div class="flex items-center gap-2">
				{#if hasSelection && bulkOperations.length > 0}
					{#each bulkOperations as operation (operation.id)}
						{@const isDisabled = operation.disabled ? operation.disabled(selected) : false}
						<Button
							variant={operation.variant === 'destructive' ? 'outline' : (operation.variant || 'outline')}
							size="sm"
							on:click={() => handleBulkOperation(operation)}
							disabled={isDisabled}
							class={operation.variant === 'destructive' ? 'text-destructive hover:text-destructive' : ''}
						>
							{#if operation.icon}
								{@const IconComponent = operation.icon as import('svelte').Component<{ class?: string }>}
								<svelte:component this={IconComponent} class="w-4 h-4 mr-2" />
							{/if}
							{operation.label}
						</Button>
					{/each}
				{/if}
				{#if showCreateButton && createTemplate}
					<Button variant="outline" size="sm" on:click={handleCreate}>
						<Plus class="w-4 h-4 mr-2" />
						{createTemplate.title || 'Create'}
					</Button>
				{/if}
				{#if showRefreshButton}
					<Button variant="outline" size="sm" on:click={handleRefresh} disabled={refreshing}>
						<RefreshCw class={cn("w-4 h-4 mr-2", refreshing && "animate-spin")} />
						Refresh
					</Button>
				{/if}
			</div>
		</div>

		<!-- Table -->
		<div class="rounded-xl border bg-card text-card-foreground shadow">
			<div class="relative w-full overflow-auto">
				<table class="w-full caption-bottom text-sm table-fixed">
					<thead class="[&_tr]:border-b">
						<tr class="border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted">
							{#if showCheckboxes}
								<th class="h-10 px-4 text-left align-middle font-medium text-muted-foreground w-12">
									<input
										type="checkbox"
										class="peer h-4 w-4 shrink-0 rounded-sm border border-primary shadow focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50"
										checked={allSelected}
										on:change={handleSelectAll}
										aria-label="Select all"
									/>
								</th>
							{/if}
							{#each columns as col (col.key)}
								<th class="h-10 px-4 text-left align-middle font-medium text-muted-foreground whitespace-nowrap" style="width: {col.width}">
									{col.label}
								</th>
							{/each}
						</tr>
					</thead>
					<tbody class="[&_tr:last-child]:border-0">
						{#each items as item (item[detectedPrimaryKey] || Math.random())}
							{@const isItemSelectable = !selectableFilter || selectableFilter(item)}
							<HalResourceRow
								{item}
								{columns}
								showCheckbox={showCheckboxes}
								selectable={isItemSelectable}
								selected={isSelected(item[detectedPrimaryKey])}
								onToggleSelect={() => handleToggleSelection(item[detectedPrimaryKey])}
								onRowClick={() => handleRowClick(item)}
								{customRenderers}
							/>
						{/each}
					</tbody>
				</table>
			</div>
		</div>
	</div>
{/if}
