// web.shadcn/src/features/help/topics/faq.tsx
/**
 * FAQ Help Topic Content
 */

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

export const FaqContent = () => {
    return (
        <Card>
            <CardHeader>
                <CardTitle>FAQ</CardTitle>
            </CardHeader>
            <CardContent>
                <p className="text-muted-foreground">
                    This section is a placeholder. Content will be added as the application evolves.
                </p>
            </CardContent>
        </Card>
    );
};

// web.svelte/src/lib/features/help/topics/faq.svelte
<!--
  FAQ Help Topic Content
-->

<script lang="ts">
	import Card from '$lib/components/ui/card.svelte';
	import CardHeader from '$lib/components/ui/card-header.svelte';
	import CardContent from '$lib/components/ui/card-content.svelte';
</script>

<Card>
	<CardHeader>
		<h2 class="text-lg font-semibold">FAQ</h2>
	</CardHeader>
	<CardContent>
		<p class="text-muted-foreground">
			This section is a placeholder. Content will be added as the application evolves.
		</p>
	</CardContent>
</Card>
