// web.svelte/src/lib/components/hal_forms/template_form.svelte
<script lang="ts">
	import type { HalTemplate, HalTemplateProperty } from '@houseofwolves/serverlesslaunchpad.types/hal';
	import { createEventDispatcher } from 'svelte';
	import { AlertCircle } from 'lucide-svelte';
	import Label from '$lib/components/ui/label.svelte';
	import Input from '$lib/components/ui/input.svelte';
	import Textarea from '$lib/components/ui/textarea.svelte';
	import Button from '$lib/components/ui/button.svelte';

	export let template: HalTemplate;
	export let loading = false;
	export let errors: Record<string, string> = {};
	export let onCancel: (() => void) | undefined = undefined;

	const dispatch = createEventDispatcher<{
		submit: Record<string, any>;
	}>();

	// Form data state
	let formData: Record<string, any> = {};

	// Initialize form data with default values
	$: {
		if (template.properties) {
			template.properties.forEach(prop => {
				if (formData[prop.name] === undefined) {
					formData[prop.name] = prop.value ?? '';
				}
			});
		}
	}

	function handleSubmit(event: Event) {
		event.preventDefault();
		const validationErrors = validateForm();
		if (Object.keys(validationErrors).length === 0) {
			dispatch('submit', formData);
		} else {
			errors = validationErrors;
		}
	}

	function validateForm(): Record<string, string> {
		const validationErrors: Record<string, string> = {};

		template.properties?.forEach(prop => {
			const value = formData[prop.name];

			// Required validation
			if (prop.required && (!value || value === '')) {
				validationErrors[prop.name] = `${prop.prompt || prop.name} is required`;
			}

			// Min/Max length validation
			if (value && typeof value === 'string') {
				if (prop.minLength && value.length < prop.minLength) {
					validationErrors[prop.name] = `Minimum length is ${prop.minLength}`;
				}
				if (prop.maxLength && value.length > prop.maxLength) {
					validationErrors[prop.name] = `Maximum length is ${prop.maxLength}`;
				}
			}

			// Min/Max value validation
			if (value && (prop.type === 'number' || prop.type === 'date')) {
				const numValue = typeof value === 'number' ? value : parseFloat(value);
				if (prop.min !== undefined && numValue < Number(prop.min)) {
					validationErrors[prop.name] = `Minimum value is ${prop.min}`;
				}
				if (prop.max !== undefined && numValue > Number(prop.max)) {
					validationErrors[prop.name] = `Maximum value is ${prop.max}`;
				}
			}

			// Regex validation
			if (value && prop.regex && typeof value === 'string') {
				const regex = new RegExp(prop.regex);
				if (!regex.test(value)) {
					validationErrors[prop.name] = `Invalid format`;
				}
			}

			// Options validation
			if (prop.options && value) {
				const validOptions = prop.options.map(opt => opt.value);
				if (!validOptions.includes(value)) {
					validationErrors[prop.name] = `Invalid selection`;
				}
			}
		});

		return validationErrors;
	}

	function renderField(prop: HalTemplateProperty) {
		const fieldId = `field-${prop.name}`;
		const hasError = errors[prop.name];
		const errorClass = hasError ? 'input-error' : '';

		switch (prop.type) {
			case 'hidden':
				return { type: 'hidden', inputClass: '' };
			case 'number':
				return { type: 'number', inputClass: `input input-bordered w-full ${errorClass}` };
			case 'date':
				return { type: 'date', inputClass: `input input-bordered w-full ${errorClass}` };
			case 'email':
				return { type: 'email', inputClass: `input input-bordered w-full ${errorClass}` };
			case 'url':
				return { type: 'url', inputClass: `input input-bordered w-full ${errorClass}` };
			case 'tel':
				return { type: 'tel', inputClass: `input input-bordered w-full ${errorClass}` };
			case 'textarea':
				return { type: 'textarea', inputClass: `textarea textarea-bordered w-full ${errorClass}` };
			case 'select':
				return { type: 'select', inputClass: `select select-bordered w-full ${errorClass}` };
			default:
				return { type: 'text', inputClass: `input input-bordered w-full ${errorClass}` };
		}
	}
</script>

<form on:submit={handleSubmit} class="space-y-4">
	{#if template.properties}
		{#each template.properties as prop}
			{@const field = renderField(prop)}
			{@const fieldId = `field-${prop.name}`}

			{#if prop.type === 'hidden'}
				<input
					type="hidden"
					id={fieldId}
					name={prop.name}
					bind:value={formData[prop.name]}
				/>
			{:else if prop.type === 'textarea'}
				<div class="space-y-2">
					<Label for={fieldId}>
						{prop.prompt || prop.name}
						{#if prop.required}<span class="text-destructive">*</span>{/if}
					</Label>
					<Textarea
						id={fieldId}
						name={prop.name}
						bind:value={formData[prop.name]}
						required={prop.required}
						readonly={prop.readOnly}
						minlength={prop.minLength}
						maxlength={prop.maxLength}
						rows={4}
					/>
					{#if errors[prop.name]}
						<p class="text-sm text-destructive flex items-center gap-1">
							<AlertCircle class="h-4 w-4" />
							{errors[prop.name]}
						</p>
					{/if}
				</div>
			{:else if prop.type === 'select'}
				<div class="space-y-2">
					<Label for={fieldId}>
						{prop.prompt || prop.name}
						{#if prop.required}<span class="text-destructive">*</span>{/if}
					</Label>
					<select
						id={fieldId}
						name={prop.name}
						class="flex h-10 w-full rounded-md border border-input bg-transparent px-3 py-2 text-base shadow-sm transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50 md:text-sm"
						bind:value={formData[prop.name]}
						required={prop.required}
						disabled={prop.readOnly}
					>
						<option value="">Select...</option>
						{#if prop.options}
							{#each prop.options as option}
								<option value={option.value}>
									{option.prompt || option.value}
								</option>
							{/each}
						{/if}
					</select>
					{#if errors[prop.name]}
						<p class="text-sm text-destructive flex items-center gap-1">
							<AlertCircle class="h-4 w-4" />
							{errors[prop.name]}
						</p>
					{/if}
				</div>
			{:else}
				<div class="space-y-2">
					<Label for={fieldId}>
						{prop.prompt || prop.name}
						{#if prop.required}<span class="text-destructive">*</span>{/if}
					</Label>
					<Input
						type={field.type}
						id={fieldId}
						name={prop.name}
						bind:value={formData[prop.name]}
						required={prop.required}
						readonly={prop.readOnly}
						min={prop.min}
						max={prop.max}
						minlength={prop.minLength}
						maxlength={prop.maxLength}
						pattern={prop.regex}
					/>
					{#if errors[prop.name]}
						<p class="text-sm text-destructive flex items-center gap-1">
							<AlertCircle class="h-4 w-4" />
							{errors[prop.name]}
						</p>
					{/if}
				</div>
			{/if}
		{/each}
	{/if}

	<div class="flex gap-2 justify-end pt-4">
		{#if onCancel}
			<Button
				type="button"
				variant="outline"
				on:click={onCancel}
				disabled={loading}
			>
				Cancel
			</Button>
		{/if}
		<Button
			type="submit"
			disabled={loading}
		>
			{loading ? 'Submitting...' : template.title || 'Submit'}
		</Button>
	</div>
</form>

// shadcn.web/src/components/hal_forms/template_form.tsx
import { useState, FormEvent } from 'react';
import { HalTemplate, HalTemplateProperty } from '@houseofwolves/serverlesslaunchpad.types/hal';
import { ValidationError } from '../../lib/hal_forms_client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from '@/components/ui/select';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { AlertCircle } from 'lucide-react';

/**
 * Props for TemplateForm component
 */
export interface TemplateFormProps {
    /** The HAL template to render as a form */
    template: HalTemplate;
    /** Callback when form is submitted with valid data */
    onSubmit: (data: Record<string, any>) => void | Promise<void>;
    /** Optional loading state (e.g., during API call) */
    loading?: boolean;
    /** Optional error message to display */
    error?: string | null;
    /** Optional validation errors to display per field */
    validationErrors?: ValidationError[];
    /** Optional callback when form is cancelled */
    onCancel?: () => void;
    /** Optional initial values for form fields */
    initialValues?: Record<string, any>;
}

/**
 * Generic form component that renders a HAL template as a shadcn/ui form
 *
 * Features:
 * - Automatically generates form fields from template properties
 * - Supports various input types (text, number, email, select, textarea, etc.)
 * - Handles required fields and validation
 * - Integrates with shadcn/ui components
 * - Displays validation errors per field
 *
 * @example
 * ```tsx
 * const template = {
 *   title: 'Create User',
 *   method: 'POST',
 *   target: '/users',
 *   properties: [
 *     { name: 'email', prompt: 'Email', type: 'email', required: true },
 *     { name: 'name', prompt: 'Name', required: true },
 *     { name: 'age', prompt: 'Age', type: 'number', min: 18 }
 *   ]
 * };
 *
 * function CreateUser() {
 *   const { execute, loading, error, validationErrors } = useExecuteTemplate();
 *
 *   return (
 *     <TemplateForm
 *       template={template}
 *       onSubmit={(data) => execute(template, data)}
 *       loading={loading}
 *       error={error}
 *       validationErrors={validationErrors}
 *     />
 *   );
 * }
 * ```
 */
export function TemplateForm({
    template,
    onSubmit,
    loading = false,
    error = null,
    validationErrors = [],
    onCancel,
    initialValues = {},
}: TemplateFormProps) {
    // Initialize form state with initial values or defaults
    const [formData, setFormData] = useState<Record<string, any>>(() => {
        const initial: Record<string, any> = { ...initialValues };
        template.properties?.forEach((prop) => {
            if (initial[prop.name] === undefined) {
                initial[prop.name] = prop.value ?? '';
            }
        });
        return initial;
    });

    /**
     * Handle form field changes
     */
    const handleFieldChange = (name: string, value: any) => {
        setFormData((prev) => ({
            ...prev,
            [name]: value,
        }));
    };

    /**
     * Handle form submission
     */
    const handleSubmit = async (e: FormEvent) => {
        e.preventDefault();
        await onSubmit(formData);
    };

    /**
     * Get validation error for a specific field
     */
    const getFieldError = (fieldName: string): string | undefined => {
        const error = validationErrors.find((err) => err.field === fieldName);
        return error?.message;
    };

    return (
        <form onSubmit={handleSubmit}>
            <div className="flex flex-col space-y-4">
                {/* Form Title */}
                {template.title && <h2 className="text-2xl font-semibold">{template.title}</h2>}

                {/* Global Error Alert */}
                {error && (
                    <Alert variant="destructive">
                        <AlertCircle className="h-4 w-4" />
                        <AlertTitle>Error</AlertTitle>
                        <AlertDescription>{error}</AlertDescription>
                    </Alert>
                )}

                {/* Form Fields */}
                {template.properties?.map((property) => (
                    <TemplateField
                        key={property.name}
                        property={property}
                        value={formData[property.name]}
                        onChange={(value) => handleFieldChange(property.name, value)}
                        error={getFieldError(property.name)}
                        disabled={loading || property.readOnly}
                    />
                ))}

                {/* Action Buttons */}
                <div className="flex items-center gap-2">
                    <Button type="submit" disabled={loading}>
                        {template.title || 'Submit'}
                    </Button>
                    {onCancel && (
                        <Button variant="ghost" onClick={onCancel} disabled={loading} type="button">
                            Cancel
                        </Button>
                    )}
                </div>
            </div>
        </form>
    );
}

/**
 * Props for TemplateField component
 */
interface TemplateFieldProps {
    /** The property definition from the template */
    property: HalTemplateProperty;
    /** Current value */
    value: any;
    /** Change handler */
    onChange: (value: any) => void;
    /** Optional error message */
    error?: string;
    /** Whether the field is disabled */
    disabled?: boolean;
}

/**
 * Renders an appropriate input component based on template property type
 */
function TemplateField({ property, value, onChange, error, disabled }: TemplateFieldProps) {
    const label = property.prompt || property.name;
    const required = property.required || false;

    // Hidden input (for tokens, IDs, etc.)
    if (property.type === 'hidden') {
        return <input type="hidden" name={property.name} value={value} />;
    }

    // Select/dropdown for options
    if (property.options && property.options.length > 0) {
        return (
            <div className="flex flex-col space-y-2">
                <Label htmlFor={property.name}>
                    {label}
                    {required && <span className="text-destructive ml-1">*</span>}
                </Label>
                <Select
                    value={value ? String(value) : undefined}
                    onValueChange={(val) => onChange(val)}
                    disabled={disabled}
                >
                    <SelectTrigger id={property.name}>
                        <SelectValue placeholder={`Select ${label.toLowerCase()}`} />
                    </SelectTrigger>
                    <SelectContent>
                        {property.options.map((opt) => (
                            <SelectItem key={String(opt.value)} value={String(opt.value)}>
                                {opt.prompt || String(opt.value)}
                            </SelectItem>
                        ))}
                    </SelectContent>
                </Select>
                {error && <p className="text-sm text-destructive">{error}</p>}
            </div>
        );
    }

    // Textarea for long text
    if (property.type === 'textarea') {
        return (
            <div className="flex flex-col space-y-2">
                <Label htmlFor={property.name}>
                    {label}
                    {required && <span className="text-destructive ml-1">*</span>}
                </Label>
                <Textarea
                    id={property.name}
                    placeholder={`Enter ${label.toLowerCase()}`}
                    value={value || ''}
                    onChange={(e) => onChange(e.currentTarget.value)}
                    required={required}
                    disabled={disabled}
                    minLength={property.minLength}
                    maxLength={property.maxLength}
                    rows={4}
                />
                {error && <p className="text-sm text-destructive">{error}</p>}
            </div>
        );
    }

    // Number input
    if (property.type === 'number') {
        return (
            <div className="flex flex-col space-y-2">
                <Label htmlFor={property.name}>
                    {label}
                    {required && <span className="text-destructive ml-1">*</span>}
                </Label>
                <Input
                    id={property.name}
                    type="number"
                    placeholder={`Enter ${label.toLowerCase()}`}
                    value={value ?? ''}
                    onChange={(e) => {
                        const val = e.currentTarget.value;
                        onChange(val === '' ? undefined : Number(val));
                    }}
                    required={required}
                    disabled={disabled}
                    min={property.min as number | undefined}
                    max={property.max as number | undefined}
                />
                {error && <p className="text-sm text-destructive">{error}</p>}
            </div>
        );
    }

    // Text input (default for text, email, url, tel, date, etc.)
    const inputType = property.type || 'text';
    return (
        <div className="flex flex-col space-y-2">
            <Label htmlFor={property.name}>
                {label}
                {required && <span className="text-destructive ml-1">*</span>}
            </Label>
            <Input
                id={property.name}
                type={inputType}
                placeholder={`Enter ${label.toLowerCase()}`}
                value={value || ''}
                onChange={(e) => onChange(e.currentTarget.value)}
                required={required}
                disabled={disabled}
                minLength={property.minLength}
                maxLength={property.maxLength}
            />
            {error && <p className="text-sm text-destructive">{error}</p>}
        </div>
    );
}
