// web.mantine/src/components/theme_toggle.tsx
/**
 * Theme Toggle Component
 *
 * Button that toggles between light and dark modes using Mantine's color scheme.
 * Displays sun icon in light mode, moon icon in dark mode.
 */

import { ActionIcon, useMantineColorScheme, useComputedColorScheme } from '@mantine/core';
import { IconSun, IconMoon } from '@tabler/icons-react';

export function ThemeToggle() {
    const { setColorScheme } = useMantineColorScheme();
    const computedColorScheme = useComputedColorScheme('light', { getInitialValueInEffect: true });

    const toggleColorScheme = () => {
        setColorScheme(computedColorScheme === 'dark' ? 'light' : 'dark');
    };

    return (
        <ActionIcon
            onClick={toggleColorScheme}
            variant="subtle"
            size="lg"
            aria-label="Toggle color scheme"
        >
            {computedColorScheme === 'dark' ? (
                <IconSun size={20} />
            ) : (
                <IconMoon size={20} />
            )}
        </ActionIcon>
    );
}

// web.svelte/src/lib/components/dashboard/theme-toggle.svelte
<script lang="ts">
	import { toggleMode } from 'mode-watcher';
	import { Moon, Sun } from 'lucide-svelte';
	import Button from '$lib/components/ui/button.svelte';

	let className: string | undefined = undefined;
	export { className as class };
</script>

<Button
	variant="ghost"
	size="icon"
	on:click={toggleMode}
	class={className}
	aria-label="Toggle theme"
>
	<Sun class="h-5 w-5 rotate-0 scale-100 transition-all dark:-rotate-90 dark:scale-0" />
	<Moon
		class="absolute h-5 w-5 rotate-90 scale-0 transition-all dark:rotate-0 dark:scale-100"
	/>
	<span class="sr-only">Toggle theme</span>
</Button>
