// web.svelte/src/lib/components/dashboard/breadcrumbs.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { get } from 'svelte/store';
	import { ChevronRight, Home } from 'lucide-svelte';
	import { cn } from '$lib/utils';
	import { breadcrumbsStore } from '$lib/stores/breadcrumbs_store';
	import { navigationHistoryStore } from '$lib/stores/navigation_history_store';
	import { getHref } from '$lib/utils/hal_helpers';

	let className: string | undefined = undefined;
	export { className as class };

	function handleBreadcrumbClick(href: string | null) {
		if (!href) return;

		// Get current history
		const navHistory = get(navigationHistoryStore);

		// Find this href in the history array
		const historyIndex = navHistory.history.findIndex((item) => {
			const itemHref = getHref(item.resource._links?.self);
			return itemHref === href;
		});

		if (historyIndex >= 0) {
			// Found in history - truncate to this point
			navigationHistoryStore.truncateHistory(historyIndex);

			// Mark next navigation to skip tracking (avoid duplicate)
			navigationHistoryStore.markNextNavigationSkip();

			// Navigate
			goto(href);
		} else {
			// Not in history (Dashboard or group) - just navigate
			goto(href);
		}
	}
</script>

<nav aria-label="Breadcrumb" class={cn('flex items-center space-x-2 text-sm', className)}>
	{#each $breadcrumbsStore as crumb, index}
		{#if index > 0}
			<ChevronRight class="h-4 w-4 text-muted-foreground" />
		{/if}

		{#if crumb.isLast || !crumb.href}
			<span class="font-medium text-foreground flex items-center gap-1.5">
				{#if index === 0}
					<Home class="h-4 w-4" />
				{/if}
				{crumb.label}
			</span>
		{:else}
			<button
				type="button"
				on:click={() => handleBreadcrumbClick(crumb.href)}
				class="text-muted-foreground hover:text-foreground transition-colors flex items-center gap-1.5"
			>
				{#if index === 0}
					<Home class="h-4 w-4" />
				{/if}
				{crumb.label}
			</button>
		{/if}
	{/each}
</nav>

// web.daisyui/src/components/breadcrumbs.tsx
import { useNavigate } from 'react-router-dom';
import { Home } from 'lucide-react';
import { useBreadcrumbs } from '@/hooks/use_breadcrumbs_adapter';
import { useNavigationHistory } from '@houseofwolves/serverlesslaunchpad.web.commons.react';

/**
 * Breadcrumb navigation component
 *
 * Displays breadcrumb trail built from navigation history.
 * HATEOAS-compliant: all labels and hrefs from HAL _links.self
 */
export function Breadcrumbs() {
  const breadcrumbs = useBreadcrumbs();
  const navigate = useNavigate();
  const { history, truncateHistory, markNextNavigationSkip } = useNavigationHistory();

  if (breadcrumbs.length === 0) {
    return null;
  }

  const handleClick = (href: string) => (e: React.MouseEvent) => {
    e.preventDefault();

    // Find this href in the history array
    const historyIndex = history.findIndex(item => {
      const selfLink = item.resource._links?.self;
      const itemHref = Array.isArray(selfLink) ? selfLink[0]?.href : selfLink?.href;
      return itemHref === href;
    });

    if (historyIndex >= 0) {
      // Found in history - truncate to this point
      truncateHistory(historyIndex);

      // Mark next navigation to skip tracking (avoid duplicate)
      markNextNavigationSkip();

      // Navigate
      navigate(href);
    } else {
      // Not in history (Dashboard or group) - just navigate
      navigate(href);
    }
  };

  return (
    <nav aria-label="breadcrumb">
      <div className="breadcrumbs text-sm">
        <ul>
          {breadcrumbs.map((crumb, index) => (
            <li key={index}>
              {crumb.isLast ? (
                // Current page - not clickable, bold
                <span className="font-semibold text-base-content flex items-center gap-2">
                  {index === 0 && <Home className="w-4 h-4" />}
                  {crumb.label}
                </span>
              ) : crumb.isGroup ? (
                // Group label - not clickable, muted
                <span className="text-base-content/70">
                  {crumb.label}
                </span>
              ) : (
                // Clickable breadcrumb
                <a
                  href={crumb.href!}
                  onClick={handleClick(crumb.href!)}
                  className="link link-hover text-base-content/70 hover:text-base-content flex items-center gap-2"
                >
                  {index === 0 && <Home className="w-4 h-4" />}
                  {crumb.label}
                </a>
              )}
            </li>
          ))}
        </ul>
      </div>
    </nav>
  );
}
